package main

import (
	"context"
	"fmt"
	"path/filepath"
	"sort"
	"strconv"
	"strings"
)

type firewallRuleSpec struct {
	Direction string
	Action    string
	Protocol  string
	Port      int
	Source    string
	Interface string
	Comment   string
}

type routeSpec struct {
	Destination string
	Via         string
	Dev         string
	Source      string
	Table       string
	Metric      int
}

func applyNetworkPolicy(ctx context.Context, payload instanceJobPayload) (map[string]any, error) {
	script, counts, hasPolicy, err := renderNetworkPolicyScript(payload)
	if err != nil {
		return nil, err
	}
	if !hasPolicy {
		return map[string]any{"applied": false}, nil
	}

	slug := slugifyLocal(first(payload.Slug, payload.InstanceID, payload.Name, "instance"))
	scriptPath := filepath.Join("/usr/local/lib/megavpn/netpolicy", slug+".sh")
	unitName := "megavpn-netpolicy-" + slug + ".service"
	unitPath := filepath.Join("/etc/systemd/system", unitName)
	if !isSafeNetworkPolicyManagedPath(scriptPath) || !isSafeNetworkPolicyManagedPath(unitPath) || !isSafeNetworkPolicyUnit(unitName) {
		return nil, fmt.Errorf("network policy managed path is not allowed")
	}
	if err := writeManagedFile(managedFileSpec{Path: scriptPath, Content: script, Mode: "0700"}); err != nil {
		return nil, err
	}
	if err := writeManagedFile(managedFileSpec{Path: unitPath, Content: renderNetworkPolicyUnit(unitName, scriptPath, payload), Mode: "0644"}); err != nil {
		return nil, err
	}
	_, _ = runInstallCommand(ctx, "systemctl", "daemon-reload")
	code, out := runInstallCommand(ctx, "systemctl", "enable", "--now", unitName)
	result := map[string]any{
		"applied":        code == 0,
		"unit":           unitName,
		"unit_path":      unitPath,
		"script_path":    scriptPath,
		"sysctl_count":   counts["sysctl"],
		"firewall_count": counts["firewall"],
		"route_count":    counts["routes"],
		"output":         truncate(out, 2000),
	}
	if code != 0 {
		result["error"] = "network policy apply failed"
		return result, fmt.Errorf("network policy apply failed: %s", truncate(out, 2000))
	}
	return result, nil
}

func renderNetworkPolicyUnit(unitName, scriptPath string, payload instanceJobPayload) string {
	return strings.Join([]string{
		"[Unit]",
		"Description=RTIS MegaVPN network policy for " + first(payload.Name, payload.Slug, payload.InstanceID, unitName),
		"After=network-online.target",
		"Wants=network-online.target",
		"",
		"[Service]",
		"Type=oneshot",
		"ExecStart=" + scriptPath,
		"RemainAfterExit=yes",
		"",
		"[Install]",
		"WantedBy=multi-user.target",
		"",
	}, "\n")
}

func isSafeNetworkPolicyManagedPath(path string) bool {
	path = cleanAbsPath(path)
	if path == "" || hasUnsafePathToken(path) {
		return false
	}
	if strings.HasPrefix(path, "/usr/local/lib/megavpn/netpolicy/") && strings.HasSuffix(path, ".sh") {
		return true
	}
	if strings.HasPrefix(path, "/etc/systemd/system/megavpn-netpolicy-") && strings.HasSuffix(path, ".service") {
		unit := strings.TrimPrefix(path, "/etc/systemd/system/")
		return isSafeNetworkPolicyUnit(unit)
	}
	return false
}

func isSafeNetworkPolicyUnit(unit string) bool {
	unit = strings.TrimSpace(unit)
	return strings.HasPrefix(unit, "megavpn-netpolicy-") &&
		strings.HasSuffix(unit, ".service") &&
		!strings.Contains(unit, "/") &&
		!strings.Contains(unit, "..") &&
		!strings.ContainsAny(unit, " \t\r\n;{}")
}

func renderNetworkPolicyScript(payload instanceJobPayload) (string, map[string]int, bool, error) {
	sysctlValues, err := parseSysctlSpec(payload.Spec["sysctl"])
	if err != nil {
		return "", nil, false, err
	}
	firewallRules, err := parseFirewallRules(payload.Spec["firewall_rules"])
	if err != nil {
		return "", nil, false, err
	}
	routes, err := parseRoutes(payload.Spec["routes"])
	if err != nil {
		return "", nil, false, err
	}
	counts := map[string]int{"sysctl": len(sysctlValues), "firewall": len(firewallRules), "routes": len(routes)}
	if len(sysctlValues) == 0 && len(firewallRules) == 0 && len(routes) == 0 {
		return "", counts, false, nil
	}

	lines := []string{
		"#!/usr/bin/env sh",
		"set -eu",
		"",
		"# Generated by megavpn-agent. Do not edit manually.",
	}
	if len(sysctlValues) > 0 {
		keys := make([]string, 0, len(sysctlValues))
		for key := range sysctlValues {
			keys = append(keys, key)
		}
		sort.Strings(keys)
		lines = append(lines, "", "# Kernel networking policy")
		for _, key := range keys {
			lines = append(lines, "sysctl -w "+shellQuote(key+"="+sysctlValues[key]))
		}
	}
	if len(firewallRules) > 0 {
		lines = append(lines, "", "# nftables ingress policy")
		lines = append(lines,
			"if ! command -v nft >/dev/null 2>&1; then echo 'nft is required for firewall_rules' >&2; exit 1; fi",
			"nft list table inet megavpn >/dev/null 2>&1 || nft add table inet megavpn",
		)
		for _, chain := range requiredFirewallChains(firewallRules) {
			lines = append(lines, fmt.Sprintf("nft list chain inet megavpn %s >/dev/null 2>&1 || nft add chain inet megavpn %s '{ type filter hook %s priority 0; policy accept; }'", chain, chain, chain))
		}
		for _, rule := range firewallRules {
			comment := firewallRuleComment(payload, rule)
			expr := nftRuleExpression(rule, comment)
			lines = append(lines, "if ! nft list chain inet megavpn "+rule.Direction+" | grep -Fq "+shellQuote(comment)+"; then "+expr+"; fi")
		}
	}
	if len(routes) > 0 {
		lines = append(lines, "", "# Kernel route policy")
		lines = append(lines, "if ! command -v ip >/dev/null 2>&1; then echo 'iproute2 is required for routes' >&2; exit 1; fi")
		for _, route := range routes {
			lines = append(lines, ipRouteReplaceCommand(route))
		}
	}
	return strings.Join(lines, "\n") + "\n", counts, true, nil
}

func parseSysctlSpec(raw any) (map[string]string, error) {
	if raw == nil {
		return nil, nil
	}
	m, ok := raw.(map[string]any)
	if !ok {
		return nil, fmt.Errorf("spec.sysctl must be an object")
	}
	out := map[string]string{}
	for key, value := range m {
		key = strings.TrimSpace(key)
		if !isSafeSysctlKey(key) {
			return nil, fmt.Errorf("invalid sysctl key %q", key)
		}
		text := stringify(value)
		if text == "" {
			return nil, fmt.Errorf("sysctl %s value is empty", key)
		}
		out[key] = text
	}
	return out, nil
}

func parseFirewallRules(raw any) ([]firewallRuleSpec, error) {
	items, err := objectList(raw, "spec.firewall_rules")
	if err != nil {
		return nil, err
	}
	out := make([]firewallRuleSpec, 0, len(items))
	for idx, item := range items {
		rule := firewallRuleSpec{
			Direction: strings.ToLower(first(stringify(item["direction"]), "input")),
			Action:    strings.ToLower(first(stringify(item["action"]), "allow")),
			Protocol:  strings.ToLower(first(stringify(item["protocol"]), stringify(item["proto"]))),
			Port:      intFromAny(item["port"], item["dport"], item["listen_port"]),
			Source:    stringify(firstAny(item["source"], item["src"])),
			Interface: stringify(firstAny(item["interface"], item["iifname"], item["dev"])),
			Comment:   stringify(item["comment"]),
		}
		if rule.Direction != "input" && rule.Direction != "forward" {
			return nil, fmt.Errorf("spec.firewall_rules[%d].direction must be input or forward", idx)
		}
		if rule.Action != "allow" && rule.Action != "drop" && rule.Action != "reject" {
			return nil, fmt.Errorf("spec.firewall_rules[%d].action must be allow, drop or reject", idx)
		}
		if rule.Protocol != "tcp" && rule.Protocol != "udp" {
			return nil, fmt.Errorf("spec.firewall_rules[%d].protocol must be tcp or udp", idx)
		}
		if rule.Port <= 0 || rule.Port > 65535 {
			return nil, fmt.Errorf("spec.firewall_rules[%d].port must be between 1 and 65535", idx)
		}
		if rule.Source != "" && !isSafeNetworkToken(rule.Source) {
			return nil, fmt.Errorf("spec.firewall_rules[%d].source is invalid", idx)
		}
		if rule.Interface != "" && !isSafeNetworkToken(rule.Interface) {
			return nil, fmt.Errorf("spec.firewall_rules[%d].interface is invalid", idx)
		}
		out = append(out, rule)
	}
	return out, nil
}

func parseRoutes(raw any) ([]routeSpec, error) {
	items, err := objectList(raw, "spec.routes")
	if err != nil {
		return nil, err
	}
	out := make([]routeSpec, 0, len(items))
	for idx, item := range items {
		route := routeSpec{
			Destination: first(stringify(item["destination"]), stringify(item["dst"]), stringify(item["cidr"]), stringify(item["to"])),
			Via:         first(stringify(item["via"]), stringify(item["gateway"])),
			Dev:         first(stringify(item["dev"]), stringify(item["interface"])),
			Source:      first(stringify(item["source"]), stringify(item["src"])),
			Table:       stringify(item["table"]),
			Metric:      intFromAny(item["metric"]),
		}
		if route.Destination == "" {
			return nil, fmt.Errorf("spec.routes[%d].destination is required", idx)
		}
		for _, token := range []string{route.Destination, route.Via, route.Dev, route.Source, route.Table} {
			if token != "" && !isSafeNetworkToken(token) {
				return nil, fmt.Errorf("spec.routes[%d] contains invalid token %q", idx, token)
			}
		}
		out = append(out, route)
	}
	return out, nil
}

func objectList(raw any, field string) ([]map[string]any, error) {
	if raw == nil {
		return nil, nil
	}
	list, ok := raw.([]any)
	if !ok {
		return nil, fmt.Errorf("%s must be an array", field)
	}
	out := make([]map[string]any, 0, len(list))
	for idx, item := range list {
		m, ok := item.(map[string]any)
		if !ok {
			return nil, fmt.Errorf("%s[%d] must be an object", field, idx)
		}
		out = append(out, m)
	}
	return out, nil
}

func requiredFirewallChains(rules []firewallRuleSpec) []string {
	seen := map[string]bool{}
	out := []string{}
	for _, rule := range rules {
		if !seen[rule.Direction] {
			seen[rule.Direction] = true
			out = append(out, rule.Direction)
		}
	}
	sort.Strings(out)
	return out
}

func nftRuleExpression(rule firewallRuleSpec, comment string) string {
	parts := []string{"nft", "add", "rule", "inet", "megavpn", rule.Direction}
	if rule.Interface != "" {
		parts = append(parts, "iifname", "\""+rule.Interface+"\"")
	}
	if rule.Source != "" {
		parts = append(parts, "ip", "saddr", rule.Source)
	}
	parts = append(parts, rule.Protocol, "dport", strconv.Itoa(rule.Port), nftVerdict(rule.Action), "comment", shellQuote(comment))
	return strings.Join(parts, " ")
}

func nftVerdict(action string) string {
	switch action {
	case "allow":
		return "accept"
	default:
		return action
	}
}

func firewallRuleComment(payload instanceJobPayload, rule firewallRuleSpec) string {
	base := "megavpn:" + slugifyLocal(first(payload.Slug, payload.InstanceID, payload.Name, "instance"))
	return base + ":" + rule.Direction + ":" + rule.Protocol + ":" + strconv.Itoa(rule.Port) + ":" + rule.Action
}

func ipRouteReplaceCommand(route routeSpec) string {
	parts := []string{"ip", "route", "replace", shellQuote(route.Destination)}
	if route.Via != "" {
		parts = append(parts, "via", shellQuote(route.Via))
	}
	if route.Dev != "" {
		parts = append(parts, "dev", shellQuote(route.Dev))
	}
	if route.Source != "" {
		parts = append(parts, "src", shellQuote(route.Source))
	}
	if route.Metric > 0 {
		parts = append(parts, "metric", strconv.Itoa(route.Metric))
	}
	if route.Table != "" {
		parts = append(parts, "table", shellQuote(route.Table))
	}
	return strings.Join(parts, " ")
}

func intFromAny(values ...any) int {
	for _, value := range values {
		switch x := value.(type) {
		case int:
			if x != 0 {
				return x
			}
		case int64:
			if x != 0 {
				return int(x)
			}
		case float64:
			if x != 0 {
				return int(x)
			}
		case string:
			if n, err := strconv.Atoi(strings.TrimSpace(x)); err == nil && n != 0 {
				return n
			}
		}
	}
	return 0
}

func firstAny(values ...any) any {
	for _, value := range values {
		if stringify(value) != "" {
			return value
		}
	}
	return nil
}

func isSafeSysctlKey(value string) bool {
	if value == "" {
		return false
	}
	for _, r := range value {
		if (r >= 'a' && r <= 'z') || (r >= 'A' && r <= 'Z') || (r >= '0' && r <= '9') || r == '.' || r == '_' || r == '-' {
			continue
		}
		return false
	}
	return true
}

func isSafeNetworkToken(value string) bool {
	if value == "" {
		return false
	}
	for _, r := range value {
		if (r >= 'a' && r <= 'z') || (r >= 'A' && r <= 'Z') || (r >= '0' && r <= '9') {
			continue
		}
		switch r {
		case '.', ':', '/', '_', '-', '@':
			continue
		default:
			return false
		}
	}
	return true
}

func shellQuote(value string) string {
	return "'" + strings.ReplaceAll(value, "'", "'\"'\"'") + "'"
}
