package main

import (
	"context"
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"time"
)

const emergencyManagedRuntimeConfigHeader = "# Generated by megavpn-agent. Do not edit manually."

func (c client) emergencyCleanupNode(ctx context.Context, j job, st agentState) (string, map[string]any) {
	started := time.Now()
	nodeID := stringify(j.Payload["node_id"])
	if nodeID == "" {
		nodeID = st.NodeID
	}
	if st.NodeID != "" && nodeID != "" && nodeID != st.NodeID {
		return "failed", map[string]any{"error": "cleanup node_id does not match enrolled agent", "payload_node_id": nodeID, "agent_node_id": st.NodeID}
	}
	expectedConfirmation := stringify(j.Payload["node_name"])
	if expectedConfirmation == "" {
		expectedConfirmation = st.NodeName
	}
	if expectedConfirmation == "" || stringify(j.Payload["confirmation"]) != expectedConfirmation {
		return "failed", map[string]any{"error": "cleanup confirmation is missing or invalid", "expected_node_name": expectedConfirmation}
	}

	includeAgent := boolFromAny(j.Payload["include_agent"])
	cleanupScope := normalizeEmergencyCleanupScope(stringify(j.Payload["cleanup_scope"]), includeAgent)
	result := map[string]any{
		"message":       "node emergency cleanup completed",
		"node_id":       nodeID,
		"include_agent": includeAgent,
		"cleanup_scope": cleanupScope,
	}
	instanceResults, instanceFailed := emergencyCleanupInstances(ctx, j.Payload["instances"])
	leftovers := emergencyCleanupManagedLeftovers(ctx, cleanupScope)
	result["instances"] = instanceResults
	result["leftovers"] = leftovers

	warnings := stringSliceFromAny(leftovers["warnings"])
	if instanceFailed {
		warnings = append(warnings, "one or more instance cleanup operations failed")
	}
	if includeAgent {
		agentCleanup, err := scheduleAgentSelfRemoval(ctx)
		result["agent_self_removal"] = agentCleanup
		if err != nil {
			result["error"] = err.Error()
			result["duration_ms"] = time.Since(started).Milliseconds()
			return "failed", result
		}
	}
	if len(warnings) > 0 {
		result["warnings"] = warnings
	}
	result["duration_ms"] = time.Since(started).Milliseconds()
	if instanceFailed {
		result["error"] = "node cleanup finished with failed instance cleanup operations"
		return "failed", result
	}
	return "succeeded", result
}

func emergencyCleanupInstances(ctx context.Context, raw any) ([]map[string]any, bool) {
	items, _ := raw.([]any)
	results := make([]map[string]any, 0, len(items))
	failed := false
	exec := instanceRuntimeExecutor{}
	for _, item := range items {
		payloadMap, ok := item.(map[string]any)
		if !ok {
			failed = true
			results = append(results, map[string]any{"status": "failed", "error": "instance cleanup payload is not an object"})
			continue
		}
		payloadMap["action"] = "delete"
		payload, err := decodeInstanceJobPayload(payloadMap)
		if err != nil {
			failed = true
			results = append(results, map[string]any{"status": "failed", "error": err.Error()})
			continue
		}
		status, result := exec.Delete(ctx, payload)
		if result == nil {
			result = map[string]any{}
		}
		result["status"] = status
		result["instance_id"] = payload.InstanceID
		result["service_code"] = payload.ServiceCode
		if status != "succeeded" {
			failed = true
		}
		results = append(results, result)
	}
	return results, failed
}

func emergencyCleanupManagedLeftovers(ctx context.Context, cleanupScope string) map[string]any {
	cleanupScope = normalizeEmergencyCleanupScope(cleanupScope, false)
	fullNode := cleanupScope == "full_node"
	stoppedUnits := []string{}
	removedPaths := []string{}
	skippedItems := []string{}
	warnings := []string{}
	nginxRuntime := map[string]any{}

	for _, unit := range emergencyCleanupUnitNames(cleanupScope) {
		code, out := runInstallCommand(ctx, "systemctl", "disable", "--now", unit)
		if code != 0 && !isMissingSystemdUnitOutput(out) {
			warnings = append(warnings, "systemd disable warning for "+unit+": "+firstLine(out))
		} else if code == 0 {
			stoppedUnits = append(stoppedUnits, unit)
		}
		resetCode, resetOut := runInstallCommand(ctx, "systemctl", "reset-failed", unit)
		if resetCode != 0 && !isMissingSystemdUnitOutput(resetOut) {
			warnings = append(warnings, "systemd reset-failed warning for "+unit+": "+firstLine(resetOut))
		}
		if path := emergencyManagedUnitFilePathForScope(unit, cleanupScope); path != "" {
			removed, err := removeManagedPath(path, false)
			if err != nil {
				warnings = append(warnings, path+": "+err.Error())
			} else if removed {
				removedPaths = append(removedPaths, path)
			} else {
				skippedItems = append(skippedItems, path+": not found - skip")
			}
		}
	}

	if fullNode {
		for _, path := range []string{
			"/etc/megavpn/client-access-routes.json",
			"/etc/systemd/system/megavpn-route-policy.service",
		} {
			removed, err := removeManagedPath(path, false)
			if err != nil {
				warnings = append(warnings, path+": "+err.Error())
			} else if removed {
				removedPaths = append(removedPaths, path)
			} else {
				skippedItems = append(skippedItems, path+": not found - skip")
			}
		}
	}

	managedDirs := []string{
		"/etc/megavpn/certs",
		"/var/lib/megavpn/openvpn",
	}
	if fullNode {
		managedDirs = append([]string{"/etc/megavpn/backhaul"}, managedDirs...)
	}
	for _, path := range managedDirs {
		removed, err := removeManagedPath(path, true)
		if err != nil {
			warnings = append(warnings, path+": "+err.Error())
		} else if removed {
			removedPaths = append(removedPaths, path)
		} else {
			skippedItems = append(skippedItems, path+": not found - skip")
		}
	}

	for _, path := range emergencyCleanupManagedOpenVPNRuntimeDirs(cleanupScope) {
		removed, err := removeManagedPath(path, true)
		if err != nil {
			warnings = append(warnings, path+": "+err.Error())
		} else if removed {
			removedPaths = append(removedPaths, path)
		} else {
			skippedItems = append(skippedItems, path+": not found - skip")
		}
	}

	for _, path := range emergencyCleanupManagedServiceConfigPaths(cleanupScope) {
		removed, err := removeManagedPath(path, false)
		if err != nil {
			warnings = append(warnings, path+": "+err.Error())
		} else if removed {
			removedPaths = append(removedPaths, path)
		} else {
			skippedItems = append(skippedItems, path+": not found - skip")
		}
	}

	for _, pattern := range []string{
		"/etc/nginx/conf.d/megavpn-*.conf",
		"/etc/systemd/system/megavpn-*.service",
	} {
		matches, err := filepath.Glob(pattern)
		if err != nil {
			warnings = append(warnings, pattern+": "+err.Error())
			continue
		}
		for _, path := range matches {
			if !isEmergencyManagedFilePathForScope(path, cleanupScope) {
				continue
			}
			removed, err := removeManagedPath(path, false)
			if err != nil {
				warnings = append(warnings, path+": "+err.Error())
			} else if removed {
				removedPaths = append(removedPaths, path)
			}
		}
	}

	if nginxRuntime = finalizeSharedNginxRuntime(ctx); len(nginxRuntime) > 0 {
		if errText := stringify(nginxRuntime["error"]); errText != "" {
			warnings = append(warnings, "nginx cleanup warning: "+errText)
		}
	}

	reloadResult, err := runSystemdDaemonReload(ctx)
	if err != nil {
		warnings = append(warnings, err.Error())
	}
	return map[string]any{
		"cleanup_scope":  cleanupScope,
		"stopped_units":  stoppedUnits,
		"removed_paths":  removedPaths,
		"skipped_items":  skippedItems,
		"warnings":       warnings,
		"nginx_runtime":  nginxRuntime,
		"systemd_reload": reloadResult,
	}
}

func finalizeSharedNginxRuntime(ctx context.Context) map[string]any {
	matches, err := filepath.Glob("/etc/nginx/conf.d/megavpn-*.conf")
	if err != nil {
		return map[string]any{"error": err.Error(), "pattern": "/etc/nginx/conf.d/megavpn-*.conf"}
	}
	result := map[string]any{
		"remaining_managed_configs": len(matches),
		"unit":                      "nginx",
	}
	if len(matches) > 0 {
		code, out := runInstallCommand(ctx, "nginx", "-t")
		result["test_exit_code"] = code
		result["test_output"] = truncate(strings.TrimSpace(out), 2000)
		if code != 0 {
			result["error"] = "nginx config validation failed after managed cleanup"
			result["active_state"] = currentUnitState("nginx")
			return result
		}
		reloadCode, reloadOut := runInstallCommand(ctx, "systemctl", "reload", "nginx")
		result["action"] = "reload"
		result["reload_exit_code"] = reloadCode
		result["reload_output"] = truncate(strings.TrimSpace(reloadOut), 2000)
		result["active_state"] = currentUnitState("nginx")
		if reloadCode != 0 && !isMissingSystemdUnitOutput(reloadOut) {
			result["error"] = "nginx reload failed after managed cleanup"
		}
		return result
	}
	code, out := runInstallCommand(ctx, "systemctl", "disable", "--now", "nginx")
	result["action"] = "stop"
	result["stop_exit_code"] = code
	result["stop_output"] = truncate(strings.TrimSpace(out), 2000)
	resetCode, resetOut := runInstallCommand(ctx, "systemctl", "reset-failed", "nginx")
	result["reset_failed_exit_code"] = resetCode
	result["reset_failed_output"] = truncate(strings.TrimSpace(resetOut), 2000)
	result["active_state"] = currentUnitState("nginx")
	if code != 0 && !isMissingSystemdUnitOutput(out) {
		result["error"] = "nginx stop failed after all managed configs were removed"
	} else if resetCode != 0 && !isMissingSystemdUnitOutput(resetOut) {
		result["reset_failed_warning"] = "nginx reset-failed failed after managed cleanup"
	}
	return result
}

func emergencyCleanupUnitNames(cleanupScope string) []string {
	cleanupScope = normalizeEmergencyCleanupScope(cleanupScope, false)
	seen := map[string]bool{}
	add := func(unit string) {
		unit = strings.TrimSpace(unit)
		unit = strings.TrimSuffix(unit, ".service") + ".service"
		if isEmergencyManagedUnitForScope(unit, cleanupScope) {
			seen[unit] = true
		}
	}
	for _, raw := range []string{
		runCombinedOutput("systemctl", "list-unit-files", "--type=service", "--no-legend", "--no-pager"),
		runCombinedOutput("systemctl", "list-units", "--type=service", "--all", "--no-legend", "--no-pager"),
	} {
		for _, line := range strings.Split(raw, "\n") {
			fields := strings.Fields(line)
			if len(fields) > 0 {
				add(fields[0])
			}
		}
	}
	matches, _ := filepath.Glob("/etc/systemd/system/megavpn-*.service")
	for _, path := range matches {
		add(filepath.Base(path))
	}
	for _, unit := range emergencyCleanupManagedServiceConfigUnits(cleanupScope) {
		unit = strings.TrimSpace(unit)
		if unit != "" && isSafeSystemdUnitToken(unit) {
			seen[unit] = true
		}
	}
	out := make([]string, 0, len(seen))
	for unit := range seen {
		out = append(out, unit)
	}
	sort.Strings(out)
	return out
}

func emergencyCleanupManagedServiceConfigUnits(cleanupScope string) []string {
	paths := emergencyCleanupManagedServiceConfigPaths(cleanupScope)
	out := make([]string, 0, len(paths))
	seen := map[string]bool{}
	for _, path := range paths {
		unit := emergencyManagedServiceUnitForConfigPath(path)
		if unit == "" || seen[unit] {
			continue
		}
		seen[unit] = true
		out = append(out, unit)
	}
	sort.Strings(out)
	return out
}

func emergencyManagedServiceUnitForConfigPath(path string) string {
	path = cleanAbsPath(path)
	base := strings.TrimSuffix(filepath.Base(path), ".conf")
	if base == "" || hasUnsafePathToken(base) {
		return ""
	}
	switch {
	case pathWithinRoot(path, "/etc/openvpn/server") && strings.HasSuffix(path, ".conf"):
		unit := "openvpn-server@" + base + ".service"
		if isSafeSystemdUnitToken(unit) {
			return unit
		}
	case pathWithinRoot(path, "/etc/wireguard") && strings.HasSuffix(path, ".conf"):
		unit := "wg-quick@" + base + ".service"
		if isSafeSystemdUnitToken(unit) {
			return unit
		}
	}
	return ""
}

func emergencyCleanupManagedServiceConfigPaths(cleanupScope string) []string {
	cleanupScope = normalizeEmergencyCleanupScope(cleanupScope, false)
	if cleanupScope != "services_only" && cleanupScope != "full_node" {
		return nil
	}
	out := []string{}
	for _, item := range []struct {
		pattern string
		managed func(string) bool
	}{
		{pattern: "/etc/openvpn/server/*.conf", managed: isEmergencyManagedOpenVPNConfigPath},
		{pattern: "/etc/wireguard/*.conf", managed: isEmergencyManagedWireGuardConfigPath},
	} {
		matches, err := filepath.Glob(item.pattern)
		if err != nil {
			continue
		}
		for _, path := range matches {
			if item.managed(path) {
				out = append(out, cleanAbsPath(path))
			}
		}
	}
	sort.Strings(out)
	return out
}

func emergencyCleanupManagedOpenVPNRuntimeDirs(cleanupScope string) []string {
	cleanupScope = normalizeEmergencyCleanupScope(cleanupScope, false)
	if cleanupScope != "services_only" && cleanupScope != "full_node" {
		return nil
	}
	matches, err := filepath.Glob("/etc/openvpn/server/megavpn-*")
	if err != nil {
		return nil
	}
	out := []string{}
	for _, path := range matches {
		path = cleanAbsPath(path)
		if path == "" || hasUnsafePathToken(path) || !pathWithinRoot(path, "/etc/openvpn/server") {
			continue
		}
		info, err := os.Lstat(path)
		if err != nil || !info.IsDir() || info.Mode()&os.ModeSymlink != 0 {
			continue
		}
		out = append(out, path)
	}
	sort.Strings(out)
	return out
}

func isEmergencyManagedOpenVPNConfigPath(path string) bool {
	path = cleanAbsPath(path)
	if path == "" || !pathWithinRoot(path, "/etc/openvpn/server") || !strings.HasSuffix(path, ".conf") {
		return false
	}
	body, ok := readEmergencyManagedConfig(path)
	return ok && isEmergencyManagedOpenVPNConfigContent(body)
}

func isEmergencyManagedWireGuardConfigPath(path string) bool {
	path = cleanAbsPath(path)
	if path == "" || !pathWithinRoot(path, "/etc/wireguard") || !strings.HasSuffix(path, ".conf") {
		return false
	}
	body, ok := readEmergencyManagedConfig(path)
	return ok && isEmergencyManagedWireGuardConfigContent(body)
}

func readEmergencyManagedConfig(path string) (string, bool) {
	if err := rejectSymlinkPath(path); err != nil {
		return "", false
	}
	body, err := os.ReadFile(path)
	if err != nil {
		return "", false
	}
	return string(body), true
}

func isEmergencyManagedOpenVPNConfigContent(body string) bool {
	body = strings.TrimSpace(body)
	if body == "" {
		return false
	}
	return strings.Contains(body, emergencyManagedRuntimeConfigHeader) ||
		strings.Contains(body, "/etc/openvpn/server/megavpn-")
}

func isEmergencyManagedWireGuardConfigContent(body string) bool {
	body = strings.TrimSpace(body)
	if body == "" {
		return false
	}
	return strings.Contains(body, emergencyManagedRuntimeConfigHeader) ||
		strings.Contains(body, "# megavpn-service-access-id =") ||
		strings.Contains(body, "# megavpn-client =")
}

func isEmergencyManagedUnit(unit string) bool {
	return isEmergencyManagedUnitForScope(unit, "full_node")
}

func isEmergencyManagedUnitForScope(unit, cleanupScope string) bool {
	unit = strings.TrimSpace(unit)
	if unit == "" || !isSafeSystemdUnitToken(unit) {
		return false
	}
	unit = strings.TrimSuffix(unit, ".service")
	fullNode := normalizeEmergencyCleanupScope(cleanupScope, false) == "full_node"
	if unit == "megavpn-route-policy" {
		return fullNode
	}
	if strings.HasPrefix(unit, "megavpn-backhaul-") {
		return fullNode
	}
	for _, prefix := range []string{
		"megavpn-netpolicy-",
		"megavpn-xray-",
		"megavpn-mtproto-",
		"megavpn-shadowsocks-",
		"megavpn-http-proxy-",
	} {
		if strings.HasPrefix(unit, prefix) {
			return true
		}
	}
	return false
}

func emergencyManagedUnitFilePath(unit string) string {
	return emergencyManagedUnitFilePathForScope(unit, "full_node")
}

func emergencyManagedUnitFilePathForScope(unit, cleanupScope string) string {
	unit = strings.TrimSpace(unit)
	if !isEmergencyManagedUnitForScope(unit, cleanupScope) {
		return ""
	}
	unit = strings.TrimSuffix(unit, ".service") + ".service"
	return "/etc/systemd/system/" + unit
}

func isEmergencyManagedFilePath(path string) bool {
	return isEmergencyManagedFilePathForScope(path, "full_node")
}

func isEmergencyManagedFilePathForScope(path, cleanupScope string) bool {
	path = cleanAbsPath(path)
	if path == "" || strings.Contains(path, "..") || hasUnsafePathToken(path) {
		return false
	}
	if strings.HasPrefix(path, "/etc/nginx/conf.d/megavpn-") && strings.HasSuffix(path, ".conf") {
		return true
	}
	if strings.HasPrefix(path, "/etc/systemd/system/megavpn-") && strings.HasSuffix(path, ".service") {
		return isEmergencyManagedUnitForScope(filepath.Base(path), cleanupScope)
	}
	return false
}

func normalizeEmergencyCleanupScope(value string, includeAgent bool) string {
	value = strings.ToLower(strings.TrimSpace(value))
	switch value {
	case "services_only", "service", "services", "instances", "instance_runtime":
		return "services_only"
	case "full_node", "full", "node", "all", "wipe":
		return "full_node"
	}
	if includeAgent {
		return "full_node"
	}
	return "services_only"
}

func scheduleAgentSelfRemoval(ctx context.Context) (map[string]any, error) {
	scriptPath := "/run/megavpn-agent-self-remove.sh"
	script := `#!/bin/sh
set -eu
systemctl disable --now megavpn-agent.service >/dev/null 2>&1 || true
rm -f /etc/systemd/system/megavpn-agent.service
rm -f /etc/megavpn/agent.env /etc/megavpn/agent-bootstrap.env
rm -rf /var/lib/megavpn/agent
rm -f /opt/megavpn/bin/megavpn-agent
rmdir /opt/megavpn/bin >/dev/null 2>&1 || true
rmdir /opt/megavpn >/dev/null 2>&1 || true
systemctl daemon-reload >/dev/null 2>&1 || true
rm -f "$0"
`
	if err := os.WriteFile(scriptPath, []byte(script), 0700); err != nil {
		return map[string]any{"scheduled": false, "error": err.Error()}, err
	}
	code, out := runInstallCommand(ctx, "systemd-run", "--unit", "megavpn-agent-self-remove", "--on-active=5s", "/bin/sh", scriptPath)
	result := map[string]any{
		"scheduled": code == 0,
		"script":    scriptPath,
		"output":    truncate(out, 2000),
	}
	if code != 0 {
		return result, fmt.Errorf("agent self-removal schedule failed: %s", firstLine(out))
	}
	return result, nil
}

func boolFromAny(value any) bool {
	switch x := value.(type) {
	case bool:
		return x
	case string:
		switch strings.ToLower(strings.TrimSpace(x)) {
		case "true", "1", "yes":
			return true
		}
	}
	return false
}

func stringSliceFromAny(value any) []string {
	items, ok := value.([]string)
	if ok {
		return append([]string{}, items...)
	}
	raw, ok := value.([]any)
	if !ok {
		return nil
	}
	out := make([]string, 0, len(raw))
	for _, item := range raw {
		if s := stringify(item); s != "" {
			out = append(out, s)
		}
	}
	return out
}

func mapFromAny(value any) map[string]any {
	item, ok := value.(map[string]any)
	if ok {
		return item
	}
	b, err := json.Marshal(value)
	if err != nil {
		return nil
	}
	var out map[string]any
	if err := json.Unmarshal(b, &out); err != nil {
		return nil
	}
	return out
}
