package main

import (
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

const emergencyManagedRuntimeConfigHeader = "# Generated by megavpn-agent. Do not edit manually."

func (c client) emergencyCleanupNode(ctx context.Context, j job, st agentState) (string, map[string]any) {
	outcome := c.emergencyCleanupNodeOutcome(ctx, j, st)
	return outcome.Status, outcome.Result
}

func validateEmergencyCleanupJobPayload(payload map[string]any, includeAgent bool) (string, error) {
	st := agentState{NodeID: stringify(payload["node_id"]), NodeName: stringify(payload["node_name"])}
	decoded, err := decodeEmergencyCleanupJobPayload(payload, st)
	if err != nil {
		return "", err
	}
	if decoded.IncludeAgent != includeAgent {
		return "", fmt.Errorf("include_agent mismatch")
	}
	return decoded.CleanupScope, nil
}

func emergencyCleanupPlanVersion(value any) (int, bool) {
	switch x := value.(type) {
	case int:
		return x, true
	case int32:
		return int(x), true
	case int64:
		return int(x), true
	case float64:
		return int(x), true
	case json.Number:
		n, err := x.Int64()
		if err != nil {
			return 0, false
		}
		return int(n), true
	case string:
		if strings.TrimSpace(x) == "" {
			return 0, false
		}
		var parsed int
		if _, err := fmt.Sscanf(strings.TrimSpace(x), "%d", &parsed); err != nil {
			return 0, false
		}
		return parsed, true
	default:
		return 0, false
	}
}

func emergencyCleanupInstances(ctx context.Context, raw any) ([]map[string]any, bool) {
	items, _ := raw.([]any)
	results := make([]map[string]any, 0, len(items))
	failed := false
	exec := instanceRuntimeExecutor{}
	for _, item := range items {
		payloadMap, ok := item.(map[string]any)
		if !ok {
			failed = true
			results = append(results, map[string]any{"status": "failed", "error": "instance cleanup payload is not an object"})
			continue
		}
		strictMap := make(map[string]any, len(payloadMap)+1)
		for k, v := range payloadMap {
			strictMap[k] = v
		}
		strictMap["action"] = "delete"
		payload, err := decodeInstanceJobPayload(strictMap)
		if err != nil {
			failed = true
			results = append(results, map[string]any{"status": "failed", "error": err.Error()})
			continue
		}
		status, result := exec.Delete(ctx, payload)
		if result == nil {
			result = map[string]any{}
		}
		result["status"] = status
		result["instance_id"] = payload.InstanceID
		result["service_code"] = payload.ServiceCode
		if status != "succeeded" {
			failed = true
		}
		results = append(results, result)
	}
	return results, failed
}

func emergencyCleanupManagedLeftovers(ctx context.Context, cleanupScope string) map[string]any {
	exec := newEmergencyCleanupExecutor()
	summary := &emergencyCleanupSummary{}
	nginxCandidates := map[string]struct{}{}
	unitChanged, failures, warnings := exec.cleanupManagedLeftovers(ctx, normalizeEmergencyCleanupScope(cleanupScope, false), map[string]struct{}{}, nginxCandidates, summary)
	nginx := exec.cleanupNginxManagedConfigs(ctx, nginxCandidates, summary)
	systemd := map[string]any{"daemon_reload": "not_required"}
	if unitChanged {
		code, _ := exec.command(ctx, "systemctl", "daemon-reload")
		if code != 0 {
			systemd["daemon_reload"] = "failed"
			systemd["error_code"] = "systemd_reload_failed"
			failures++
		} else {
			systemd["daemon_reload"] = "succeeded"
		}
	}
	if nginx.ErrorCode != "" {
		failures++
	}
	return map[string]any{
		"cleanup_scope": normalizeEmergencyCleanupScope(cleanupScope, false),
		"summary": map[string]any{
			"units_stopped": summary.UnitsStopped,
			"paths_removed": summary.PathsRemoved,
			"warnings":      summary.Warnings + warnings,
			"failures":      failures,
		},
		"nginx_runtime": map[string]any{
			"status":                    nginx.Status,
			"remaining_managed_configs": nginx.RemainingManagedConfig,
			"error_code":                nginx.ErrorCode,
		},
		"systemd_reload": systemd,
	}
}

func finalizeSharedNginxRuntime(ctx context.Context) map[string]any {
	matches, err := filepath.Glob("/etc/nginx/conf.d/megavpn-*.conf")
	if err != nil {
		return map[string]any{"status": "failed", "error": "nginx_glob_failed"}
	}
	result := map[string]any{
		"remaining_managed_configs": len(matches),
		"unit":                      "nginx",
		"active_state":              currentUnitState("nginx"),
	}
	if len(matches) == 0 {
		result["status"] = "unchanged"
		result["action"] = "none"
		result["note"] = "shared nginx is never stopped or disabled by cleanup"
		return result
	}
	code, _ := runInstallCommand(ctx, "nginx", "-t")
	result["validation"] = "succeeded"
	if code != 0 {
		result["status"] = "failed"
		result["validation"] = "failed"
		result["error"] = "nginx_validation_failed"
		return result
	}
	if normalizeSystemctlState(stringify(result["active_state"])) != "active" {
		result["status"] = "inactive_unchanged"
		result["action"] = "none"
		return result
	}
	reloadCode, _ := runInstallCommand(ctx, "systemctl", "reload", "nginx")
	result["action"] = "reload"
	result["reload"] = "succeeded"
	result["status"] = "reloaded"
	if reloadCode != 0 {
		result["reload"] = "failed"
		result["status"] = "failed"
		result["error"] = "nginx_reload_failed"
	}
	return result
}

func emergencyCleanupUnitNames(cleanupScope string) []string {
	cleanupScope = normalizeEmergencyCleanupScope(cleanupScope, false)
	seen := map[string]bool{}
	add := func(unit string) {
		unit = strings.TrimSpace(unit)
		unit = strings.TrimSuffix(unit, ".service") + ".service"
		if isEmergencyManagedUnitForScope(unit, cleanupScope) {
			seen[unit] = true
		}
	}
	for _, raw := range []string{
		runCombinedOutput("systemctl", "list-unit-files", "--type=service", "--no-legend", "--no-pager"),
		runCombinedOutput("systemctl", "list-units", "--type=service", "--all", "--no-legend", "--no-pager"),
	} {
		for _, line := range strings.Split(raw, "\n") {
			fields := strings.Fields(line)
			if len(fields) > 0 {
				add(fields[0])
			}
		}
	}
	matches, _ := filepath.Glob("/etc/systemd/system/megavpn-*.service")
	for _, path := range matches {
		add(filepath.Base(path))
	}
	for _, unit := range emergencyCleanupManagedServiceConfigUnits(cleanupScope) {
		unit = strings.TrimSpace(unit)
		if unit != "" && isSafeSystemdUnitToken(unit) {
			seen[unit] = true
		}
	}
	out := make([]string, 0, len(seen))
	for unit := range seen {
		out = append(out, unit)
	}
	sort.Strings(out)
	return out
}

func emergencyCleanupManagedServiceConfigUnits(cleanupScope string) []string {
	paths := emergencyCleanupManagedServiceConfigPaths(cleanupScope)
	out := make([]string, 0, len(paths))
	seen := map[string]bool{}
	for _, path := range paths {
		unit := emergencyManagedServiceUnitForConfigPath(path)
		if unit == "" || seen[unit] {
			continue
		}
		seen[unit] = true
		out = append(out, unit)
	}
	sort.Strings(out)
	return out
}

func emergencyManagedServiceUnitForConfigPath(path string) string {
	path = cleanAbsPath(path)
	base := strings.TrimSuffix(filepath.Base(path), ".conf")
	if base == "" || hasUnsafePathToken(base) {
		return ""
	}
	switch {
	case pathWithinRoot(path, "/etc/openvpn/server") && strings.HasSuffix(path, ".conf"):
		unit := "openvpn-server@" + base + ".service"
		if isSafeSystemdUnitToken(unit) {
			return unit
		}
	case pathWithinRoot(path, "/etc/wireguard") && strings.HasSuffix(path, ".conf"):
		unit := "wg-quick@" + base + ".service"
		if isSafeSystemdUnitToken(unit) {
			return unit
		}
	}
	return ""
}

func emergencyCleanupManagedServiceConfigPaths(cleanupScope string) []string {
	cleanupScope = normalizeEmergencyCleanupScope(cleanupScope, false)
	if cleanupScope != "services_only" && cleanupScope != "full_node" {
		return nil
	}
	out := []string{}
	for _, item := range []struct {
		pattern string
		managed func(string) bool
	}{
		{pattern: "/etc/openvpn/server/*.conf", managed: isEmergencyManagedOpenVPNConfigPath},
		{pattern: "/etc/wireguard/*.conf", managed: isEmergencyManagedWireGuardConfigPath},
	} {
		matches, err := filepath.Glob(item.pattern)
		if err != nil {
			continue
		}
		for _, path := range matches {
			if item.managed(path) {
				out = append(out, cleanAbsPath(path))
			}
		}
	}
	sort.Strings(out)
	return out
}

func emergencyCleanupManagedOpenVPNRuntimeDirs(cleanupScope string) []string {
	cleanupScope = normalizeEmergencyCleanupScope(cleanupScope, false)
	if cleanupScope != "services_only" && cleanupScope != "full_node" {
		return nil
	}
	matches, err := filepath.Glob("/etc/openvpn/server/megavpn-*")
	if err != nil {
		return nil
	}
	out := []string{}
	for _, path := range matches {
		path = cleanAbsPath(path)
		if path == "" || hasUnsafePathToken(path) || !pathWithinRoot(path, "/etc/openvpn/server") {
			continue
		}
		info, err := os.Lstat(path)
		if err != nil || !info.IsDir() || info.Mode()&os.ModeSymlink != 0 {
			continue
		}
		out = append(out, path)
	}
	sort.Strings(out)
	return out
}

func isEmergencyManagedOpenVPNConfigPath(path string) bool {
	path = cleanAbsPath(path)
	if path == "" || !pathWithinRoot(path, "/etc/openvpn/server") || !strings.HasSuffix(path, ".conf") {
		return false
	}
	body, ok := readEmergencyManagedConfig(path)
	return ok && isEmergencyManagedOpenVPNConfigContent(body)
}

func isEmergencyManagedWireGuardConfigPath(path string) bool {
	path = cleanAbsPath(path)
	if path == "" || !pathWithinRoot(path, "/etc/wireguard") || !strings.HasSuffix(path, ".conf") {
		return false
	}
	body, ok := readEmergencyManagedConfig(path)
	return ok && isEmergencyManagedWireGuardConfigContent(body)
}

func readEmergencyManagedConfig(path string) (string, bool) {
	if err := rejectSymlinkPath(path); err != nil {
		return "", false
	}
	body, err := os.ReadFile(path)
	if err != nil {
		return "", false
	}
	return string(body), true
}

func isEmergencyManagedOpenVPNConfigContent(body string) bool {
	body = strings.TrimSpace(body)
	if body == "" {
		return false
	}
	return strings.Contains(body, emergencyManagedRuntimeConfigHeader) ||
		strings.Contains(body, "/etc/openvpn/server/megavpn-")
}

func isEmergencyManagedWireGuardConfigContent(body string) bool {
	body = strings.TrimSpace(body)
	if body == "" {
		return false
	}
	return strings.Contains(body, emergencyManagedRuntimeConfigHeader) ||
		strings.Contains(body, "# megavpn-service-access-id =") ||
		strings.Contains(body, "# megavpn-client =")
}

func isEmergencyManagedUnit(unit string) bool {
	return isEmergencyManagedUnitForScope(unit, "full_node")
}

func isEmergencyManagedUnitForScope(unit, cleanupScope string) bool {
	unit = strings.TrimSpace(unit)
	if unit == "" || !isSafeSystemdUnitToken(unit) {
		return false
	}
	unit = strings.TrimSuffix(unit, ".service")
	fullNode := normalizeEmergencyCleanupScope(cleanupScope, false) == "full_node"
	if unit == "megavpn-route-policy" {
		return fullNode
	}
	if strings.HasPrefix(unit, "megavpn-backhaul-") {
		return fullNode
	}
	for _, prefix := range []string{
		"megavpn-netpolicy-",
		"megavpn-xray-",
		"megavpn-mtproto-",
		"megavpn-shadowsocks-",
		"megavpn-http-proxy-",
	} {
		if strings.HasPrefix(unit, prefix) {
			return true
		}
	}
	return false
}

func emergencyManagedUnitFilePath(unit string) string {
	return emergencyManagedUnitFilePathForScope(unit, "full_node")
}

func emergencyManagedUnitFilePathForScope(unit, cleanupScope string) string {
	unit = strings.TrimSpace(unit)
	if !isEmergencyManagedUnitForScope(unit, cleanupScope) {
		return ""
	}
	unit = strings.TrimSuffix(unit, ".service") + ".service"
	return "/etc/systemd/system/" + unit
}

func isEmergencyManagedFilePath(path string) bool {
	return isEmergencyManagedFilePathForScope(path, "full_node")
}

func isEmergencyManagedFilePathForScope(path, cleanupScope string) bool {
	path = cleanAbsPath(path)
	if path == "" || strings.Contains(path, "..") || hasUnsafePathToken(path) {
		return false
	}
	if strings.HasPrefix(path, "/etc/nginx/conf.d/megavpn-") && strings.HasSuffix(path, ".conf") {
		return true
	}
	if strings.HasPrefix(path, "/etc/systemd/system/megavpn-") && strings.HasSuffix(path, ".service") {
		return isEmergencyManagedUnitForScope(filepath.Base(path), cleanupScope)
	}
	return false
}

func normalizeEmergencyCleanupScope(value string, includeAgent bool) string {
	value = strings.ToLower(strings.TrimSpace(value))
	switch value {
	case "services_only":
		return "services_only"
	case "full_node":
		return "full_node"
	}
	return ""
}

func scheduleAgentSelfRemoval(ctx context.Context) (map[string]any, error) {
	err := defaultAgentSelfRemovalManager.activateAfterAck(ctx, "manual-compatibility-call")
	result := map[string]any{"scheduled": errors.Is(err, ErrAgentSelfRemovalScheduled)}
	if err != nil && !errors.Is(err, ErrAgentSelfRemovalScheduled) {
		result["error"] = "agent_self_removal_schedule_failed"
		return result, err
	}
	return result, nil
}

func boolFromAny(value any) bool {
	switch x := value.(type) {
	case bool:
		return x
	case string:
		switch strings.ToLower(strings.TrimSpace(x)) {
		case "true", "1", "yes":
			return true
		}
	}
	return false
}

func stringSliceFromAny(value any) []string {
	items, ok := value.([]string)
	if ok {
		return append([]string{}, items...)
	}
	raw, ok := value.([]any)
	if !ok {
		return nil
	}
	out := make([]string, 0, len(raw))
	for _, item := range raw {
		if s := stringify(item); s != "" {
			out = append(out, s)
		}
	}
	return out
}

func mapFromAny(value any) map[string]any {
	item, ok := value.(map[string]any)
	if ok {
		return item
	}
	b, err := json.Marshal(value)
	if err != nil {
		return nil
	}
	var out map[string]any
	if err := json.Unmarshal(b, &out); err != nil {
		return nil
	}
	return out
}
