package main

import (
	"fmt"
	"net"
	"net/netip"
	"strconv"
	"strings"
)

const (
	routePolicyScriptPath        = "/usr/local/lib/megavpn/route-policy/client-access-routes.sh"
	routePolicyCleanupScriptPath = "/usr/local/lib/megavpn/route-policy/client-access-routes-cleanup.sh"
	routePolicyUnitName          = "megavpn-route-policy.service"
	routePolicyUnitPath          = "/etc/systemd/system/" + routePolicyUnitName
	routePolicyTimerName         = "megavpn-route-policy.timer"
	routePolicyTimerPath         = "/etc/systemd/system/" + routePolicyTimerName
	routePolicySystemPriority    = 21900
	routePolicySystemPriorityTo  = 21949
	routePolicyPriority          = 22000
	routePolicyPriorityTo        = 22999
)

type routePolicyKernelCandidate struct {
	Dev    string
	Via    string
	Table  string
	Metric int
	Peer   string
}

type routePolicyKernelRule struct {
	RouteID     string
	Source      string
	Destination string
	Protocol    string
	Ports       string
	Table       string
	Candidates  []routePolicyKernelCandidate
	Priority    int
	Mark        string
	Comment     string
}

type routePolicyKernelPlan struct {
	Script          string
	RuleCount       int
	SystemRuleCount int
	MarkedCount     int
	SkippedCount    int
	Reasons         []string
}

type routePolicyCleanupSnapshot struct {
	Routes       []any
	SystemRoutes []any
}

type routePolicyCleanupTarget struct {
	Destination string
	Table       string
}

func renderRoutePolicyKernelScript(routes []any, systemRoutes []any, revision string, cleanupSnapshots ...routePolicyCleanupSnapshot) (routePolicyKernelPlan, error) {
	systemRules := []routePolicyKernelRule{}
	rules := []routePolicyKernelRule{}
	skipped := 0
	reasons := []string{}
	for _, item := range systemRoutes {
		route, _ := item.(map[string]any)
		rule, ok, reason, err := routePolicyKernelRuleFromSystemRoute(route, len(systemRules))
		if err != nil {
			return routePolicyKernelPlan{}, err
		}
		if !ok {
			skipped++
			if reason != "" {
				reasons = append(reasons, reason)
			}
			continue
		}
		systemRules = append(systemRules, rule)
	}
	for _, item := range routes {
		route, _ := item.(map[string]any)
		if route == nil || stringify(nestedMap(route, "enforcement")["mode"]) != "l3_l4_candidate" {
			continue
		}
		rule, ok, reason, err := routePolicyKernelRuleFromRoute(route, len(rules))
		if err != nil {
			return routePolicyKernelPlan{}, err
		}
		if !ok {
			skipped++
			if reason != "" {
				reasons = append(reasons, reason)
			}
			continue
		}
		rules = append(rules, rule)
	}
	cleanupTargets := routePolicyCleanupTargetsFromRules(systemRules, rules)
	for _, snapshot := range cleanupSnapshots {
		targets, targetReasons := routePolicyCleanupTargetsFromSnapshot(snapshot)
		cleanupTargets = append(cleanupTargets, targets...)
		skipped += len(targetReasons)
		reasons = append(reasons, targetReasons...)
	}
	cleanupTargets = dedupeRoutePolicyCleanupTargets(cleanupTargets)
	marked := 0
	lines := []string{
		"#!/usr/bin/env sh",
		"set -eu",
		"",
		"# Generated by megavpn-agent. Do not edit manually.",
		"# Revision: " + strings.TrimSpace(revision),
		"if ! command -v ip >/dev/null 2>&1; then echo 'iproute2 is required for route policy enforcement' >&2; exit 1; fi",
	}
	if len(rules) > 0 {
		lines = append(lines, "sysctl -w net.ipv4.ip_forward=1 >/dev/null")
	}
	lines = append(lines,
		"",
		"# Remove old MegaVPN system source-route rules from the reserved priority range.",
		"p="+strconv.Itoa(routePolicySystemPriority),
		"while [ \"$p\" -le "+strconv.Itoa(routePolicySystemPriorityTo)+" ]; do",
		"  while ip rule delete priority \"$p\" >/dev/null 2>&1; do :; done",
		"  p=$((p + 1))",
		"done",
		"",
		"# Remove old MegaVPN route-policy rules from the reserved priority range.",
		"p="+strconv.Itoa(routePolicyPriority),
		"while [ \"$p\" -le "+strconv.Itoa(routePolicyPriorityTo)+" ]; do",
		"  while ip rule delete priority \"$p\" >/dev/null 2>&1; do :; done",
		"  p=$((p + 1))",
		"done",
	)
	if routePolicyRequiresNFT(systemRules, rules) {
		lines = append(lines,
			"",
			"# Rebuild MegaVPN nftables marking chains for route policy.",
			"if ! command -v nft >/dev/null 2>&1; then echo 'nft is required for route policy enforcement' >&2; exit 1; fi",
			"nft list table inet megavpn >/dev/null 2>&1 || nft add table inet megavpn",
			"nft list chain inet megavpn route_policy_prerouting >/dev/null 2>&1 || nft add chain inet megavpn route_policy_prerouting '{ type filter hook prerouting priority mangle; policy accept; }'",
			"nft list chain inet megavpn route_policy_output >/dev/null 2>&1 || nft add chain inet megavpn route_policy_output '{ type route hook output priority mangle; policy accept; }'",
			"nft flush chain inet megavpn route_policy_prerouting",
			"nft flush chain inet megavpn route_policy_output",
		)
	} else {
		lines = append(lines,
			"",
			"# Flush stale MegaVPN nftables marking chains when nft is present.",
			"if command -v nft >/dev/null 2>&1; then",
			"  nft list chain inet megavpn route_policy_prerouting >/dev/null 2>&1 && nft flush chain inet megavpn route_policy_prerouting || true",
			"  nft list chain inet megavpn route_policy_output >/dev/null 2>&1 && nft flush chain inet megavpn route_policy_output || true",
			"fi",
		)
	}
	lines = append(lines,
		"",
		"route_policy_delete_route() {",
		"  dst=\"$1\"; table=\"$2\"; metric=\"$3\"; dev=\"$4\"; via=\"$5\"",
		"  if [ -n \"$via\" ]; then",
		"    ip route delete \"$dst\" via \"$via\" dev \"$dev\" table \"$table\" metric \"$metric\" >/dev/null 2>&1 || true",
		"  else",
		"    ip route delete \"$dst\" dev \"$dev\" table \"$table\" metric \"$metric\" >/dev/null 2>&1 || true",
		"  fi",
		"}",
		"",
		"route_policy_flush_destination() {",
		"  dst=\"$1\"; table=\"$2\"",
		"  while ip route delete \"$dst\" table \"$table\" >/dev/null 2>&1; do :; done",
		"}",
		"",
		"route_policy_probe_cache='|'",
		"route_policy_candidate_ready() {",
		"  dev=\"$1\"; peer=\"$2\"",
		"  if ! ip link show dev \"$dev\" >/dev/null 2>&1; then return 1; fi",
		"  if [ -z \"$peer\" ] || ! command -v ping >/dev/null 2>&1; then return 0; fi",
		"  key=\"$dev,$peer\"",
		"  case \"$route_policy_probe_cache\" in",
		"    *\"|$key=1|\"*) return 0 ;;",
		"    *\"|$key=0|\"*) return 1 ;;",
		"  esac",
		"  if ping -I \"$dev\" -c 1 -W 1 \"$peer\" >/dev/null 2>&1; then",
		"    route_policy_probe_cache=\"${route_policy_probe_cache}${key}=1|\"",
		"    return 0",
		"  fi",
		"  route_policy_probe_cache=\"${route_policy_probe_cache}${key}=0|\"",
		"  return 1",
		"}",
		"",
		"route_policy_replace_route() {",
		"  dst=\"$1\"; table=\"$2\"; metric=\"$3\"; dev=\"$4\"; via=\"$5\"; peer=\"$6\"",
		"  if ! route_policy_candidate_ready \"$dev\" \"$peer\"; then",
		"    route_policy_delete_route \"$dst\" \"$table\" \"$metric\" \"$dev\" \"$via\"",
		"    return 1",
		"  fi",
		"  if [ -n \"$via\" ]; then",
		"    ip route replace \"$dst\" via \"$via\" dev \"$dev\" table \"$table\" metric \"$metric\"",
		"  else",
		"    ip route replace \"$dst\" dev \"$dev\" table \"$table\" metric \"$metric\"",
		"  fi",
		"}",
		"",
		"# Route tables and policy rules.",
	)
	for _, target := range cleanupTargets {
		lines = append(lines, "route_policy_flush_destination "+shellQuote(target.Destination)+" "+shellQuote(target.Table))
	}
	for _, rule := range systemRules {
		marked++
		lines = append(lines, routePolicyRuleCommands(rule, "route_policy_output")...)
	}
	for _, rule := range rules {
		marked++
		lines = append(lines, routePolicyRuleCommands(rule, "route_policy_prerouting")...)
	}
	return routePolicyKernelPlan{
		Script:          strings.Join(lines, "\n") + "\n",
		RuleCount:       len(rules),
		SystemRuleCount: len(systemRules),
		MarkedCount:     marked,
		SkippedCount:    skipped,
		Reasons:         reasons,
	}, nil
}

func renderRoutePolicyCleanupScript(snapshot routePolicyCleanupSnapshot, revision string) routePolicyKernelPlan {
	targets, reasons := routePolicyCleanupTargetsFromSnapshot(snapshot)
	targets = dedupeRoutePolicyCleanupTargets(targets)
	lines := []string{
		"#!/usr/bin/env sh",
		"set -eu",
		"",
		"# Generated by megavpn-agent. Do not edit manually.",
		"# Route policy cleanup revision: " + strings.TrimSpace(revision),
		"if command -v ip >/dev/null 2>&1; then",
		"  p=" + strconv.Itoa(routePolicySystemPriority),
		"  while [ \"$p\" -le " + strconv.Itoa(routePolicySystemPriorityTo) + " ]; do",
		"    while ip rule delete priority \"$p\" >/dev/null 2>&1; do :; done",
		"    p=$((p + 1))",
		"  done",
		"  p=" + strconv.Itoa(routePolicyPriority),
		"  while [ \"$p\" -le " + strconv.Itoa(routePolicyPriorityTo) + " ]; do",
		"    while ip rule delete priority \"$p\" >/dev/null 2>&1; do :; done",
		"    p=$((p + 1))",
		"  done",
	}
	for _, target := range targets {
		lines = append(lines, "  while ip route delete "+shellQuote(target.Destination)+" table "+shellQuote(target.Table)+" >/dev/null 2>&1; do :; done")
	}
	lines = append(lines,
		"fi",
		"if command -v nft >/dev/null 2>&1; then",
		"  nft list chain inet megavpn route_policy_prerouting >/dev/null 2>&1 && nft flush chain inet megavpn route_policy_prerouting || true",
		"  nft list chain inet megavpn route_policy_output >/dev/null 2>&1 && nft flush chain inet megavpn route_policy_output || true",
		"fi",
		"",
	)
	return routePolicyKernelPlan{
		Script:       strings.Join(lines, "\n"),
		MarkedCount:  len(targets),
		SkippedCount: len(reasons),
		Reasons:      reasons,
	}
}

func routePolicyCleanupTargetsFromRules(systemRules []routePolicyKernelRule, rules []routePolicyKernelRule) []routePolicyCleanupTarget {
	targets := make([]routePolicyCleanupTarget, 0, len(systemRules)+len(rules))
	for _, rule := range systemRules {
		targets = append(targets, routePolicyCleanupTarget{Destination: rule.Destination, Table: rule.Table})
	}
	for _, rule := range rules {
		targets = append(targets, routePolicyCleanupTarget{Destination: rule.Destination, Table: rule.Table})
	}
	return targets
}

func routePolicyCleanupTargetsFromSnapshot(snapshot routePolicyCleanupSnapshot) ([]routePolicyCleanupTarget, []string) {
	targets := []routePolicyCleanupTarget{}
	reasons := []string{}
	add := func(destination, table, label string) {
		destination = strings.TrimSpace(destination)
		table = strings.TrimSpace(table)
		if destination == "" || table == "" || strings.EqualFold(table, "main") {
			if label != "" {
				reasons = append(reasons, label+" cleanup skipped: destination or table is empty")
			}
			return
		}
		if !isSafeNetworkToken(table) || !isSafeNetworkToken(destination) {
			if label != "" {
				reasons = append(reasons, label+" cleanup skipped: unsafe destination or table token")
			}
			return
		}
		targets = append(targets, routePolicyCleanupTarget{Destination: destination, Table: table})
	}
	for _, item := range snapshot.SystemRoutes {
		route, _ := item.(map[string]any)
		if route == nil || !strings.EqualFold(stringify(route["status"]), "active") {
			continue
		}
		destination := normalizeRoutePolicyIPPrefix(first(stringify(route["destination"]), "0.0.0.0/0"))
		add(destination, stringify(route["table"]), "system route")
	}
	for _, item := range snapshot.Routes {
		route, _ := item.(map[string]any)
		if route == nil ||
			!strings.EqualFold(stringify(route["status"]), "active") ||
			!strings.EqualFold(stringify(route["action"]), "allow") ||
			stringify(nestedMap(route, "enforcement")["mode"]) != "l3_l4_candidate" {
			continue
		}
		egress := nestedMap(route, "egress")
		if !strings.EqualFold(stringify(egress["status"]), "candidate") {
			continue
		}
		destination := normalizeRoutePolicyDestination(stringify(route["destination_type"]), stringify(route["destination"]))
		add(destination, stringify(egress["table"]), "client route")
	}
	return targets, reasons
}

func dedupeRoutePolicyCleanupTargets(targets []routePolicyCleanupTarget) []routePolicyCleanupTarget {
	out := make([]routePolicyCleanupTarget, 0, len(targets))
	seen := map[string]bool{}
	for _, target := range targets {
		key := target.Destination + "|" + target.Table
		if target.Destination == "" || target.Table == "" || seen[key] {
			continue
		}
		seen[key] = true
		out = append(out, target)
	}
	return out
}

func routePolicyKernelRuleFromSystemRoute(route map[string]any, idx int) (routePolicyKernelRule, bool, string, error) {
	if route == nil {
		return routePolicyKernelRule{}, false, "system route is empty", nil
	}
	if !strings.EqualFold(stringify(route["status"]), "active") {
		return routePolicyKernelRule{}, false, "system route is not active", nil
	}
	source := normalizeRoutePolicyIPPrefix(first(stringify(route["source"]), stringify(route["source_address"])))
	if source == "" {
		return routePolicyKernelRule{}, false, "system route source is not an IPv4 address or prefix", nil
	}
	destination := normalizeRoutePolicyIPPrefix(first(stringify(route["destination"]), "0.0.0.0/0"))
	if destination == "" {
		return routePolicyKernelRule{}, false, "system route destination is not an IPv4 prefix", nil
	}
	table := strings.TrimSpace(stringify(route["table"]))
	if table == "" || strings.EqualFold(table, "main") {
		return routePolicyKernelRule{}, false, "system route requires a non-main table", nil
	}
	if !isSafeNetworkToken(table) {
		return routePolicyKernelRule{}, false, "", fmt.Errorf("system route contains unsafe table token")
	}
	candidates, err := routePolicyKernelCandidatesFromEgress(route, table)
	if err != nil {
		return routePolicyKernelRule{}, false, "", err
	}
	if len(candidates) == 0 {
		return routePolicyKernelRule{}, false, "system route requires a managed backhaul candidate or explicit interface", nil
	}
	priority := routePolicySystemPriority + idx
	if priority > routePolicySystemPriorityTo {
		return routePolicyKernelRule{}, false, "", fmt.Errorf("too many system route policy rules for reserved priority range")
	}
	comment := "megavpn:route-policy:system:" + slugifyLocal(first(stringify(route["system_route_id"]), stringify(route["kind"]), strconv.Itoa(idx)))
	return routePolicyKernelRule{
		RouteID:     stringify(route["system_route_id"]),
		Source:      source,
		Destination: destination,
		Protocol:    "any",
		Table:       table,
		Candidates:  candidates,
		Priority:    priority,
		Mark:        fmt.Sprintf("0x%08x", 0x4d550000+idx+1),
		Comment:     comment,
	}, true, "", nil
}

func routePolicyKernelRuleFromRoute(route map[string]any, idx int) (routePolicyKernelRule, bool, string, error) {
	if !strings.EqualFold(stringify(route["status"]), "active") || !strings.EqualFold(stringify(route["action"]), "allow") {
		return routePolicyKernelRule{}, false, "route is not an active allow policy", nil
	}
	source := normalizeRoutePolicyIPPrefix(stringify(nestedMap(route, "source_identity")["value"]))
	if source == "" {
		return routePolicyKernelRule{}, false, "route source identity is not an IPv4 address or prefix", nil
	}
	destination := normalizeRoutePolicyDestination(stringify(route["destination_type"]), stringify(route["destination"]))
	if destination == "" {
		return routePolicyKernelRule{}, false, "route destination is not an IPv4 prefix or endpoint", nil
	}
	egress := nestedMap(route, "egress")
	if !strings.EqualFold(stringify(egress["status"]), "candidate") {
		return routePolicyKernelRule{}, false, "route egress output is not candidate", nil
	}
	table := strings.TrimSpace(stringify(egress["table"]))
	if table == "" || strings.EqualFold(table, "main") {
		return routePolicyKernelRule{}, false, "route egress requires a non-main interface and table", nil
	}
	if !isSafeNetworkToken(table) {
		return routePolicyKernelRule{}, false, "", fmt.Errorf("route policy egress contains unsafe table token")
	}
	candidates, err := routePolicyKernelCandidatesFromEgress(egress, table)
	if err != nil {
		return routePolicyKernelRule{}, false, "", err
	}
	if len(candidates) == 0 {
		return routePolicyKernelRule{}, false, "route egress requires a managed backhaul candidate or explicit interface", nil
	}
	protocol := strings.ToLower(strings.TrimSpace(stringify(route["protocol"])))
	if protocol == "" {
		protocol = "any"
	}
	if protocol != "any" && protocol != "tcp" && protocol != "udp" && protocol != "icmp" {
		return routePolicyKernelRule{}, false, "route protocol is not enforceable", nil
	}
	ports, err := normalizeRoutePolicyPorts(stringify(route["ports"]))
	if err != nil {
		return routePolicyKernelRule{}, false, "", err
	}
	if ports != "" && protocol != "tcp" && protocol != "udp" {
		return routePolicyKernelRule{}, false, "route ports require tcp or udp protocol", nil
	}
	priority := routePolicyPriority + idx
	if priority > routePolicyPriorityTo {
		return routePolicyKernelRule{}, false, "", fmt.Errorf("too many route policy rules for reserved priority range")
	}
	comment := "megavpn:route-policy:" + slugifyLocal(first(stringify(route["route_id"]), stringify(route["client_id"]), strconv.Itoa(idx)))
	return routePolicyKernelRule{
		RouteID:     stringify(route["route_id"]),
		Source:      source,
		Destination: destination,
		Protocol:    protocol,
		Ports:       ports,
		Table:       table,
		Candidates:  candidates,
		Priority:    priority,
		Mark:        fmt.Sprintf("0x%08x", 0x4d560000+idx+1),
		Comment:     comment,
	}, true, "", nil
}

func routePolicyKernelCandidatesFromEgress(egress map[string]any, table string) ([]routePolicyKernelCandidate, error) {
	candidates := []routePolicyKernelCandidate{}
	if rawList, ok := egress["managed_backhauls"].([]any); ok && len(rawList) > 0 {
		for _, item := range rawList {
			raw, _ := item.(map[string]any)
			candidate, ok, err := routePolicyKernelCandidateFromMap(raw, table)
			if err != nil {
				return nil, err
			}
			if ok {
				candidates = append(candidates, candidate)
			}
		}
		if len(candidates) > 0 {
			return candidates, nil
		}
	}
	raw := map[string]any{
		"interface":    egress["interface"],
		"next_hop":     egress["next_hop"],
		"route_metric": nestedMap(egress, "managed_backhaul")["route_metric"],
		"peer":         first(stringify(nestedMap(egress, "managed_backhaul")["egress_address"]), stringify(egress["peer"]), stringify(egress["peer_address"])),
	}
	returned, ok, err := routePolicyKernelCandidateFromMap(raw, table)
	if err != nil {
		return nil, err
	}
	if ok {
		candidates = append(candidates, returned)
	}
	return candidates, nil
}

func routePolicyKernelCandidateFromMap(raw map[string]any, table string) (routePolicyKernelCandidate, bool, error) {
	if raw == nil {
		return routePolicyKernelCandidate{}, false, nil
	}
	dev := strings.TrimSpace(stringify(raw["interface"]))
	if dev == "" {
		dev = strings.TrimSpace(stringify(raw["dev"]))
	}
	if dev == "" {
		return routePolicyKernelCandidate{}, false, nil
	}
	if !isSafeNetworkToken(dev) {
		return routePolicyKernelCandidate{}, false, fmt.Errorf("route policy egress contains unsafe dev token")
	}
	via := strings.TrimSpace(first(stringify(raw["next_hop"]), stringify(raw["via"])))
	if via != "" && !isSafeNetworkToken(via) {
		return routePolicyKernelCandidate{}, false, fmt.Errorf("route policy egress contains unsafe next-hop token")
	}
	metric := intFromAny(raw["route_metric"], raw["metric"])
	if metric <= 0 {
		metric = 50
	}
	peer := routePolicyPeerAddress(first(stringify(raw["peer"]), stringify(raw["peer_address"]), stringify(raw["egress_address"])))
	if peer != "" && !isSafeNetworkToken(peer) {
		return routePolicyKernelCandidate{}, false, fmt.Errorf("route policy egress contains unsafe peer token")
	}
	return routePolicyKernelCandidate{
		Dev:    dev,
		Via:    via,
		Table:  table,
		Metric: metric,
		Peer:   peer,
	}, true, nil
}

func routePolicyPeerAddress(value string) string {
	value = strings.TrimSpace(value)
	if value == "" {
		return ""
	}
	if prefix, err := netip.ParsePrefix(value); err == nil && prefix.Addr().Is4() {
		return prefix.Addr().String()
	}
	if addr, err := netip.ParseAddr(value); err == nil && addr.Is4() {
		return addr.String()
	}
	return ""
}

func normalizeRoutePolicyDestination(destinationType, destination string) string {
	switch strings.ToLower(strings.TrimSpace(destinationType)) {
	case "cidr":
		return normalizeRoutePolicyIPPrefix(destination)
	case "endpoint":
		host := endpointHostLocal(destination)
		return normalizeRoutePolicyIPPrefix(host)
	default:
		return ""
	}
}

func normalizeRoutePolicyIPPrefix(value string) string {
	value = strings.TrimSpace(value)
	if value == "" {
		return ""
	}
	if prefix, err := netip.ParsePrefix(value); err == nil && prefix.Addr().Is4() {
		return prefix.Masked().String()
	}
	if addr, err := netip.ParseAddr(value); err == nil && addr.Is4() {
		return addr.String() + "/32"
	}
	return ""
}

func endpointHostLocal(destination string) string {
	host := strings.TrimSpace(destination)
	if hp, err := netip.ParseAddrPort(host); err == nil {
		return hp.Addr().String()
	}
	if splitHost, splitPort, err := net.SplitHostPort(host); err == nil {
		if port, parseErr := strconv.Atoi(splitPort); parseErr == nil && port >= 1 && port <= 65535 {
			return strings.Trim(splitHost, "[]")
		}
	}
	if strings.Count(host, ":") == 1 {
		splitHost, splitPort, _ := strings.Cut(host, ":")
		if port, err := strconv.Atoi(splitPort); err == nil && port >= 1 && port <= 65535 {
			return strings.TrimSpace(splitHost)
		}
	}
	return host
}

func normalizeRoutePolicyPorts(raw string) (string, error) {
	raw = strings.TrimSpace(strings.ToLower(raw))
	if raw == "" || raw == "any" || raw == "*" {
		return "", nil
	}
	parts := strings.Split(raw, ",")
	out := make([]string, 0, len(parts))
	for _, part := range parts {
		part = strings.TrimSpace(part)
		if part == "" {
			continue
		}
		if strings.Contains(part, "-") {
			left, right, ok := strings.Cut(part, "-")
			if !ok {
				return "", fmt.Errorf("invalid route policy port range %q", part)
			}
			from, err := parseRoutePolicyPort(left)
			if err != nil {
				return "", err
			}
			to, err := parseRoutePolicyPort(right)
			if err != nil {
				return "", err
			}
			if from > to {
				return "", fmt.Errorf("invalid route policy port range %q", part)
			}
			out = append(out, strconv.Itoa(from)+"-"+strconv.Itoa(to))
			continue
		}
		port, err := parseRoutePolicyPort(part)
		if err != nil {
			return "", err
		}
		out = append(out, strconv.Itoa(port))
	}
	if len(out) == 0 {
		return "", nil
	}
	if len(out) == 1 {
		return out[0], nil
	}
	return "{ " + strings.Join(out, ", ") + " }", nil
}

func parseRoutePolicyPort(raw string) (int, error) {
	port, err := strconv.Atoi(strings.TrimSpace(raw))
	if err != nil || port < 1 || port > 65535 {
		return 0, fmt.Errorf("route policy port %q must be between 1 and 65535", raw)
	}
	return port, nil
}

func routePolicyRequiresNFT(systemRules []routePolicyKernelRule, rules []routePolicyKernelRule) bool {
	return len(systemRules)+len(rules) > 0
}

func ipRoutePolicyRouteCommands(rule routePolicyKernelRule) []string {
	out := make([]string, 0, len(rule.Candidates))
	for _, candidate := range rule.Candidates {
		table := first(candidate.Table, rule.Table)
		out = append(out, "route_policy_replace_route "+shellQuote(rule.Destination)+" "+shellQuote(table)+" "+strconv.Itoa(candidate.Metric)+" "+shellQuote(candidate.Dev)+" "+shellQuote(candidate.Via)+" "+shellQuote(candidate.Peer))
	}
	return out
}

func routePolicyRuleCommands(rule routePolicyKernelRule, chain string) []string {
	lines := []string{"route_policy_rule_ready=0"}
	for _, command := range ipRoutePolicyRouteCommands(rule) {
		lines = append(lines, "if "+command+"; then route_policy_rule_ready=1; fi")
	}
	lines = append(lines,
		"if [ \"$route_policy_rule_ready\" -eq 1 ]; then",
		"  "+nftRoutePolicyMarkCommand(rule, chain),
		"  ip rule add fwmark "+rule.Mark+" table "+shellQuote(rule.Table)+" priority "+strconv.Itoa(rule.Priority),
		"else",
		"  echo "+shellQuote("route policy rule "+first(rule.RouteID, rule.Comment, rule.Mark)+" has no ready managed backhaul candidate")+" >&2",
		"  exit 1",
		"fi",
	)
	return lines
}

func nftRoutePolicyMarkCommand(rule routePolicyKernelRule, chain string) string {
	parts := []string{
		"nft", "add", "rule", "inet", "megavpn", chain,
		"ip", "saddr", rule.Source,
		"ip", "daddr", rule.Destination,
	}
	switch rule.Protocol {
	case "tcp", "udp":
		if rule.Ports == "" {
			parts = append(parts, "ip", "protocol", rule.Protocol)
			break
		}
		parts = append(parts, rule.Protocol, "dport", rule.Ports)
	case "icmp":
		parts = append(parts, "ip", "protocol", "icmp")
	}
	parts = append(parts, "meta", "mark", "set", rule.Mark, "comment", nftStringLiteral(rule.Comment))
	return strings.Join(parts, " ")
}

func renderRoutePolicyUnit() string {
	return strings.Join([]string{
		"[Unit]",
		"Description=MegaVPN route policy enforcement",
		"After=network-online.target",
		"Wants=network-online.target",
		"",
		"[Service]",
		"Type=oneshot",
		"ExecStart=" + routePolicyScriptPath,
		"",
		"[Install]",
		"WantedBy=multi-user.target",
		"",
	}, "\n")
}

func renderRoutePolicyTimer() string {
	return strings.Join([]string{
		"[Unit]",
		"Description=MegaVPN route policy refresh",
		"",
		"[Timer]",
		"OnBootSec=20s",
		"OnUnitActiveSec=20s",
		"AccuracySec=5s",
		"Unit=" + routePolicyUnitName,
		"",
		"[Install]",
		"WantedBy=timers.target",
		"",
	}, "\n")
}

func nestedMap(parent map[string]any, key string) map[string]any {
	child, _ := parent[key].(map[string]any)
	if child == nil {
		return map[string]any{}
	}
	return child
}
