package main

import (
	"fmt"
	"net"
	"net/netip"
	"strconv"
	"strings"
)

const (
	routePolicyScriptPath = "/usr/local/lib/megavpn/route-policy/client-access-routes.sh"
	routePolicyUnitName   = "megavpn-route-policy.service"
	routePolicyUnitPath   = "/etc/systemd/system/" + routePolicyUnitName
	routePolicyPriority   = 22000
	routePolicyPriorityTo = 22999
)

type routePolicyKernelRule struct {
	RouteID     string
	Source      string
	Destination string
	Protocol    string
	Ports       string
	Dev         string
	Via         string
	Table       string
	Metric      int
	Priority    int
	Mark        string
	Comment     string
}

type routePolicyKernelPlan struct {
	Script       string
	RuleCount    int
	MarkedCount  int
	SkippedCount int
	Reasons      []string
}

func renderRoutePolicyKernelScript(routes []any, revision string) (routePolicyKernelPlan, error) {
	rules := []routePolicyKernelRule{}
	skipped := 0
	reasons := []string{}
	for _, item := range routes {
		route, _ := item.(map[string]any)
		if route == nil || stringify(nestedMap(route, "enforcement")["mode"]) != "l3_l4_candidate" {
			continue
		}
		rule, ok, reason, err := routePolicyKernelRuleFromRoute(route, len(rules))
		if err != nil {
			return routePolicyKernelPlan{}, err
		}
		if !ok {
			skipped++
			if reason != "" {
				reasons = append(reasons, reason)
			}
			continue
		}
		rules = append(rules, rule)
	}
	if len(rules) == 0 {
		return routePolicyKernelPlan{SkippedCount: skipped, Reasons: reasons}, nil
	}

	marked := 0
	lines := []string{
		"#!/usr/bin/env sh",
		"set -eu",
		"",
		"# Generated by megavpn-agent. Do not edit manually.",
		"# Revision: " + strings.TrimSpace(revision),
		"if ! command -v ip >/dev/null 2>&1; then echo 'iproute2 is required for route policy enforcement' >&2; exit 1; fi",
		"sysctl -w net.ipv4.ip_forward=1 >/dev/null",
		"",
		"# Remove old MegaVPN route-policy rules from the reserved priority range.",
		"p=" + strconv.Itoa(routePolicyPriority),
		"while [ \"$p\" -le " + strconv.Itoa(routePolicyPriorityTo) + " ]; do",
		"  while ip rule delete priority \"$p\" >/dev/null 2>&1; do :; done",
		"  p=$((p + 1))",
		"done",
	}
	if routePolicyRequiresNFT(rules) {
		lines = append(lines,
			"",
			"# Rebuild MegaVPN nftables marking chain for port-specific policies.",
			"if ! command -v nft >/dev/null 2>&1; then echo 'nft is required for port-specific route policy enforcement' >&2; exit 1; fi",
			"nft list table inet megavpn >/dev/null 2>&1 || nft add table inet megavpn",
			"nft list chain inet megavpn route_policy_prerouting >/dev/null 2>&1 || nft add chain inet megavpn route_policy_prerouting '{ type filter hook prerouting priority mangle; policy accept; }'",
			"nft flush chain inet megavpn route_policy_prerouting",
		)
	}
	lines = append(lines, "", "# Route tables and policy rules.")
	for _, rule := range rules {
		lines = append(lines, ipRoutePolicyRouteCommand(rule))
		if rule.Ports == "" {
			lines = append(lines, "ip rule add from "+shellQuote(rule.Source)+" to "+shellQuote(rule.Destination)+" table "+shellQuote(rule.Table)+" priority "+strconv.Itoa(rule.Priority))
			continue
		}
		marked++
		lines = append(lines, nftRoutePolicyMarkCommand(rule))
		lines = append(lines, "ip rule add fwmark "+rule.Mark+" table "+shellQuote(rule.Table)+" priority "+strconv.Itoa(rule.Priority))
	}
	return routePolicyKernelPlan{
		Script:       strings.Join(lines, "\n") + "\n",
		RuleCount:    len(rules),
		MarkedCount:  marked,
		SkippedCount: skipped,
		Reasons:      reasons,
	}, nil
}

func routePolicyKernelRuleFromRoute(route map[string]any, idx int) (routePolicyKernelRule, bool, string, error) {
	if !strings.EqualFold(stringify(route["status"]), "active") || !strings.EqualFold(stringify(route["action"]), "allow") {
		return routePolicyKernelRule{}, false, "route is not an active allow policy", nil
	}
	source := normalizeRoutePolicyIPPrefix(stringify(nestedMap(route, "source_identity")["value"]))
	if source == "" {
		return routePolicyKernelRule{}, false, "route source identity is not an IPv4 address or prefix", nil
	}
	destination := normalizeRoutePolicyDestination(stringify(route["destination_type"]), stringify(route["destination"]))
	if destination == "" {
		return routePolicyKernelRule{}, false, "route destination is not an IPv4 prefix or endpoint", nil
	}
	egress := nestedMap(route, "egress")
	if !strings.EqualFold(stringify(egress["status"]), "candidate") {
		return routePolicyKernelRule{}, false, "route egress output is not candidate", nil
	}
	dev := strings.TrimSpace(stringify(egress["interface"]))
	table := strings.TrimSpace(stringify(egress["table"]))
	if dev == "" || table == "" || strings.EqualFold(table, "main") {
		return routePolicyKernelRule{}, false, "route egress requires a non-main interface and table", nil
	}
	if !isSafeNetworkToken(dev) || !isSafeNetworkToken(table) {
		return routePolicyKernelRule{}, false, "", fmt.Errorf("route policy egress contains unsafe dev/table token")
	}
	via := strings.TrimSpace(stringify(egress["next_hop"]))
	if via != "" && !isSafeNetworkToken(via) {
		return routePolicyKernelRule{}, false, "", fmt.Errorf("route policy egress contains unsafe next-hop token")
	}
	protocol := strings.ToLower(strings.TrimSpace(stringify(route["protocol"])))
	if protocol == "" {
		protocol = "any"
	}
	if protocol != "any" && protocol != "tcp" && protocol != "udp" && protocol != "icmp" {
		return routePolicyKernelRule{}, false, "route protocol is not enforceable", nil
	}
	ports, err := normalizeRoutePolicyPorts(stringify(route["ports"]))
	if err != nil {
		return routePolicyKernelRule{}, false, "", err
	}
	if ports != "" && protocol != "tcp" && protocol != "udp" {
		return routePolicyKernelRule{}, false, "route ports require tcp or udp protocol", nil
	}
	priority := routePolicyPriority + idx
	if priority > routePolicyPriorityTo {
		return routePolicyKernelRule{}, false, "", fmt.Errorf("too many route policy rules for reserved priority range")
	}
	metric := intFromAny(nestedMap(egress, "managed_backhaul")["route_metric"])
	if metric <= 0 {
		metric = 50
	}
	comment := "megavpn:route-policy:" + slugifyLocal(first(stringify(route["route_id"]), stringify(route["client_id"]), strconv.Itoa(idx)))
	return routePolicyKernelRule{
		RouteID:     stringify(route["route_id"]),
		Source:      source,
		Destination: destination,
		Protocol:    protocol,
		Ports:       ports,
		Dev:         dev,
		Via:         via,
		Table:       table,
		Metric:      metric,
		Priority:    priority,
		Mark:        fmt.Sprintf("0x%08x", 0x4d560000+idx+1),
		Comment:     comment,
	}, true, "", nil
}

func normalizeRoutePolicyDestination(destinationType, destination string) string {
	switch strings.ToLower(strings.TrimSpace(destinationType)) {
	case "cidr":
		return normalizeRoutePolicyIPPrefix(destination)
	case "endpoint":
		host := endpointHostLocal(destination)
		return normalizeRoutePolicyIPPrefix(host)
	default:
		return ""
	}
}

func normalizeRoutePolicyIPPrefix(value string) string {
	value = strings.TrimSpace(value)
	if value == "" {
		return ""
	}
	if prefix, err := netip.ParsePrefix(value); err == nil && prefix.Addr().Is4() {
		return prefix.Masked().String()
	}
	if addr, err := netip.ParseAddr(value); err == nil && addr.Is4() {
		return addr.String() + "/32"
	}
	return ""
}

func endpointHostLocal(destination string) string {
	host := strings.TrimSpace(destination)
	if hp, err := netip.ParseAddrPort(host); err == nil {
		return hp.Addr().String()
	}
	if splitHost, splitPort, err := net.SplitHostPort(host); err == nil {
		if port, parseErr := strconv.Atoi(splitPort); parseErr == nil && port >= 1 && port <= 65535 {
			return strings.Trim(splitHost, "[]")
		}
	}
	if strings.Count(host, ":") == 1 {
		splitHost, splitPort, _ := strings.Cut(host, ":")
		if port, err := strconv.Atoi(splitPort); err == nil && port >= 1 && port <= 65535 {
			return strings.TrimSpace(splitHost)
		}
	}
	return host
}

func normalizeRoutePolicyPorts(raw string) (string, error) {
	raw = strings.TrimSpace(strings.ToLower(raw))
	if raw == "" || raw == "any" || raw == "*" {
		return "", nil
	}
	parts := strings.Split(raw, ",")
	out := make([]string, 0, len(parts))
	for _, part := range parts {
		part = strings.TrimSpace(part)
		if part == "" {
			continue
		}
		if strings.Contains(part, "-") {
			left, right, ok := strings.Cut(part, "-")
			if !ok {
				return "", fmt.Errorf("invalid route policy port range %q", part)
			}
			from, err := parseRoutePolicyPort(left)
			if err != nil {
				return "", err
			}
			to, err := parseRoutePolicyPort(right)
			if err != nil {
				return "", err
			}
			if from > to {
				return "", fmt.Errorf("invalid route policy port range %q", part)
			}
			out = append(out, strconv.Itoa(from)+"-"+strconv.Itoa(to))
			continue
		}
		port, err := parseRoutePolicyPort(part)
		if err != nil {
			return "", err
		}
		out = append(out, strconv.Itoa(port))
	}
	if len(out) == 0 {
		return "", nil
	}
	if len(out) == 1 {
		return out[0], nil
	}
	return "{ " + strings.Join(out, ", ") + " }", nil
}

func parseRoutePolicyPort(raw string) (int, error) {
	port, err := strconv.Atoi(strings.TrimSpace(raw))
	if err != nil || port < 1 || port > 65535 {
		return 0, fmt.Errorf("route policy port %q must be between 1 and 65535", raw)
	}
	return port, nil
}

func routePolicyRequiresNFT(rules []routePolicyKernelRule) bool {
	for _, rule := range rules {
		if rule.Ports != "" {
			return true
		}
	}
	return false
}

func ipRoutePolicyRouteCommand(rule routePolicyKernelRule) string {
	parts := []string{"ip", "route", "replace", shellQuote(rule.Destination)}
	if rule.Via != "" {
		parts = append(parts, "via", shellQuote(rule.Via))
	}
	parts = append(parts, "dev", shellQuote(rule.Dev), "table", shellQuote(rule.Table), "metric", strconv.Itoa(rule.Metric))
	return strings.Join(parts, " ")
}

func nftRoutePolicyMarkCommand(rule routePolicyKernelRule) string {
	parts := []string{
		"nft", "add", "rule", "inet", "megavpn", "route_policy_prerouting",
		"ip", "saddr", rule.Source,
		"ip", "daddr", rule.Destination,
	}
	if rule.Protocol == "tcp" || rule.Protocol == "udp" {
		parts = append(parts, rule.Protocol, "dport", rule.Ports)
	}
	parts = append(parts, "meta", "mark", "set", rule.Mark, "comment", shellQuote(rule.Comment))
	return strings.Join(parts, " ")
}

func renderRoutePolicyUnit() string {
	return strings.Join([]string{
		"[Unit]",
		"Description=MegaVPN route policy enforcement",
		"After=network-online.target",
		"Wants=network-online.target",
		"",
		"[Service]",
		"Type=oneshot",
		"ExecStart=" + routePolicyScriptPath,
		"RemainAfterExit=yes",
		"",
		"[Install]",
		"WantedBy=multi-user.target",
		"",
	}, "\n")
}

func nestedMap(parent map[string]any, key string) map[string]any {
	child, _ := parent[key].(map[string]any)
	if child == nil {
		return map[string]any{}
	}
	return child
}
